name: "✨ Предложение фичи"
description: "Есть идея, как улучшить проект?"
labels: ["enhancement"]
body:
  - type: textarea
    id: description
    attributes:
      label: Описание
      description: Что хочешь добавить или изменить?
      placeholder: "Было бы круто, если бот мог бы..."
    validations:
      required: true
  - type: textarea
    id: motivation
    attributes:
      label: Зачем это нужно?
      description: Какую проблему это решает?
    validations:
      required: false
  - type: textarea
    id: alternatives
    attributes:
      label: Альтернативы
      description: Рассматривал ли другие варианты решения?
    validations:
      required: false
