name: "✨ Feature Request"
description: "Got an idea to improve the project?"
labels: ["enhancement"]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: What would you like to add or change?
      placeholder: "It would be great if the bot could..."
    validations:
      required: true
  - type: textarea
    id: motivation
    attributes:
      label: Motivation
      description: What problem does this solve?
    validations:
      required: false
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives
      description: Have you considered other solutions?
    validations:
      required: false
